package org.dispatch.faithfarm.domain;

// Generated Oct 24, 2013 9:59:32 AM by Hibernate Tools 3.4.0.CR1

/**
 * DonationTicket generated by hbm2java
 */
public class DonationTicket implements java.io.Serializable {

	private Long donationId;
	private String lastname;
	private String firstname;
	private String suffix;
	private String contactPhone;
	private String phoneOther;
	private String emailAddress;
	private String addressLine1;
	private String addressLine2;
	private String city;
	private String state;
	private String zipcode;
	private String majorIntersection;
	private String subdivision;
	private String streetSuffix;
	private String structureType;
	private String unit;
	private String building;
	private String floor;
	private String elevatorFlag;
	private String gatedFlag;
	private String gateInstructions;
	private String dispatchDate;
	private String status;
	private String specialFlag;
	private String callRequirements;
	private String ac;
	private String bedding;
	private String beddingQtyType;
	private String books;
	private String booksQtyType;
	private String clothing;
	private String clothingQtyType;
	private String computer;
	private String desk;
	private String chest;
	private String armoire;
	private String dresser;
	private String mirror;
	private String nightstand;
	private String headboard;
	private String footboard;
	private String rails;
	private String lamp;
	private String lawnFurniture;
	private String mattress;
	private String mattressQtySize;
	private String miscHouseholdItems;
	private String refridgerator;
	private String stove;
	private String recliner;
	private String sofa;
	private String loveseat;
	private String wallUnit;
	private String tables;
	private String chair;
	private String television;
	private String televisionSize;
	private String electronics;
	private String washer;
	private String dryer;
	private String exerciseEquipment;
	private String specialNotes;
	private String creationDate;
	private String createdBy;
	private String lastUpdatedDate;
	private String updatedBy;
	private String farmBase;
	private String tableType;
	private String chairType;
	private String location;
	private String bookcase;
	private String ottoman;
	private String miscHouseholdItemQtySize;
	private String wallUnitQtySize;
	private String gateCode;

	public DonationTicket() {
	}

	public DonationTicket(String farmBase) {
		this.farmBase = farmBase;
	}

	public DonationTicket(String lastname, String firstname, String suffix,
			String contactPhone, String phoneOther, String emailAddress,
			String addressLine1, String addressLine2, String city,
			String state, String zipcode, String majorIntersection,
			String subdivision, String streetSuffix, String structureType,
			String unit, String building, String floor, String elevatorFlag,
			String gatedFlag, String gateInstructions, String dispatchDate,
			String status, String specialFlag, String callRequirements,
			String ac, String bedding, String beddingQtyType, String books,
			String booksQtyType, String clothing, String clothingQtyType,
			String computer, String desk, String chest, String armoire,
			String dresser, String mirror, String nightstand, String headboard,
			String footboard, String rails, String lamp, String lawnFurniture,
			String mattress, String mattressQtySize, String miscHouseholdItems,
			String refridgerator, String stove, String recliner, String sofa,
			String loveseat, String wallUnit, String tables, String chair,
			String television, String televisionSize, String electronics,
			String washer, String dryer, String exerciseEquipment,
			String specialNotes, String creationDate, String createdBy,
			String lastUpdatedDate, String updatedBy, String farmBase,
			String tableType, String chairType, String location,
			String bookcase, String ottoman, String miscHouseholdItemQtySize,
			String wallUnitQtySize, String gateCode) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.suffix = suffix;
		this.contactPhone = contactPhone;
		this.phoneOther = phoneOther;
		this.emailAddress = emailAddress;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.majorIntersection = majorIntersection;
		this.subdivision = subdivision;
		this.streetSuffix = streetSuffix;
		this.structureType = structureType;
		this.unit = unit;
		this.building = building;
		this.floor = floor;
		this.elevatorFlag = elevatorFlag;
		this.gatedFlag = gatedFlag;
		this.gateInstructions = gateInstructions;
		this.dispatchDate = dispatchDate;
		this.status = status;
		this.specialFlag = specialFlag;
		this.callRequirements = callRequirements;
		this.ac = ac;
		this.bedding = bedding;
		this.beddingQtyType = beddingQtyType;
		this.books = books;
		this.booksQtyType = booksQtyType;
		this.clothing = clothing;
		this.clothingQtyType = clothingQtyType;
		this.computer = computer;
		this.desk = desk;
		this.chest = chest;
		this.armoire = armoire;
		this.dresser = dresser;
		this.mirror = mirror;
		this.nightstand = nightstand;
		this.headboard = headboard;
		this.footboard = footboard;
		this.rails = rails;
		this.lamp = lamp;
		this.lawnFurniture = lawnFurniture;
		this.mattress = mattress;
		this.mattressQtySize = mattressQtySize;
		this.miscHouseholdItems = miscHouseholdItems;
		this.refridgerator = refridgerator;
		this.stove = stove;
		this.recliner = recliner;
		this.sofa = sofa;
		this.loveseat = loveseat;
		this.wallUnit = wallUnit;
		this.tables = tables;
		this.chair = chair;
		this.television = television;
		this.televisionSize = televisionSize;
		this.electronics = electronics;
		this.washer = washer;
		this.dryer = dryer;
		this.exerciseEquipment = exerciseEquipment;
		this.specialNotes = specialNotes;
		this.creationDate = creationDate;
		this.createdBy = createdBy;
		this.lastUpdatedDate = lastUpdatedDate;
		this.updatedBy = updatedBy;
		this.farmBase = farmBase;
		this.tableType = tableType;
		this.chairType = chairType;
		this.location = location;
		this.bookcase = bookcase;
		this.ottoman = ottoman;
		this.miscHouseholdItemQtySize = miscHouseholdItemQtySize;
		this.wallUnitQtySize = wallUnitQtySize;
		this.gateCode = gateCode;
	}

	public Long getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Long donationId) {
		this.donationId = donationId;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getPhoneOther() {
		return this.phoneOther;
	}

	public void setPhoneOther(String phoneOther) {
		this.phoneOther = phoneOther;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getMajorIntersection() {
		return this.majorIntersection;
	}

	public void setMajorIntersection(String majorIntersection) {
		this.majorIntersection = majorIntersection;
	}

	public String getSubdivision() {
		return this.subdivision;
	}

	public void setSubdivision(String subdivision) {
		this.subdivision = subdivision;
	}

	public String getStreetSuffix() {
		return this.streetSuffix;
	}

	public void setStreetSuffix(String streetSuffix) {
		this.streetSuffix = streetSuffix;
	}

	public String getStructureType() {
		return this.structureType;
	}

	public void setStructureType(String structureType) {
		this.structureType = structureType;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getBuilding() {
		return this.building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getElevatorFlag() {
		return this.elevatorFlag;
	}

	public void setElevatorFlag(String elevatorFlag) {
		this.elevatorFlag = elevatorFlag;
	}

	public String getGatedFlag() {
		return this.gatedFlag;
	}

	public void setGatedFlag(String gatedFlag) {
		this.gatedFlag = gatedFlag;
	}

	public String getGateInstructions() {
		return this.gateInstructions;
	}

	public void setGateInstructions(String gateInstructions) {
		this.gateInstructions = gateInstructions;
	}

	public String getDispatchDate() {
		return this.dispatchDate;
	}

	public void setDispatchDate(String dispatchDate) {
		this.dispatchDate = dispatchDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSpecialFlag() {
		return this.specialFlag;
	}

	public void setSpecialFlag(String specialFlag) {
		this.specialFlag = specialFlag;
	}

	public String getCallRequirements() {
		return this.callRequirements;
	}

	public void setCallRequirements(String callRequirements) {
		this.callRequirements = callRequirements;
	}

	public String getAc() {
		return this.ac;
	}

	public void setAc(String ac) {
		this.ac = ac;
	}

	public String getBedding() {
		return this.bedding;
	}

	public void setBedding(String bedding) {
		this.bedding = bedding;
	}

	public String getBeddingQtyType() {
		return this.beddingQtyType;
	}

	public void setBeddingQtyType(String beddingQtyType) {
		this.beddingQtyType = beddingQtyType;
	}

	public String getBooks() {
		return this.books;
	}

	public void setBooks(String books) {
		this.books = books;
	}

	public String getBooksQtyType() {
		return this.booksQtyType;
	}

	public void setBooksQtyType(String booksQtyType) {
		this.booksQtyType = booksQtyType;
	}

	public String getClothing() {
		return this.clothing;
	}

	public void setClothing(String clothing) {
		this.clothing = clothing;
	}

	public String getClothingQtyType() {
		return this.clothingQtyType;
	}

	public void setClothingQtyType(String clothingQtyType) {
		this.clothingQtyType = clothingQtyType;
	}

	public String getComputer() {
		return this.computer;
	}

	public void setComputer(String computer) {
		this.computer = computer;
	}

	public String getDesk() {
		return this.desk;
	}

	public void setDesk(String desk) {
		this.desk = desk;
	}

	public String getChest() {
		return this.chest;
	}

	public void setChest(String chest) {
		this.chest = chest;
	}

	public String getArmoire() {
		return this.armoire;
	}

	public void setArmoire(String armoire) {
		this.armoire = armoire;
	}

	public String getDresser() {
		return this.dresser;
	}

	public void setDresser(String dresser) {
		this.dresser = dresser;
	}

	public String getMirror() {
		return this.mirror;
	}

	public void setMirror(String mirror) {
		this.mirror = mirror;
	}

	public String getNightstand() {
		return this.nightstand;
	}

	public void setNightstand(String nightstand) {
		this.nightstand = nightstand;
	}

	public String getHeadboard() {
		return this.headboard;
	}

	public void setHeadboard(String headboard) {
		this.headboard = headboard;
	}

	public String getFootboard() {
		return this.footboard;
	}

	public void setFootboard(String footboard) {
		this.footboard = footboard;
	}

	public String getRails() {
		return this.rails;
	}

	public void setRails(String rails) {
		this.rails = rails;
	}

	public String getLamp() {
		return this.lamp;
	}

	public void setLamp(String lamp) {
		this.lamp = lamp;
	}

	public String getLawnFurniture() {
		return this.lawnFurniture;
	}

	public void setLawnFurniture(String lawnFurniture) {
		this.lawnFurniture = lawnFurniture;
	}

	public String getMattress() {
		return this.mattress;
	}

	public void setMattress(String mattress) {
		this.mattress = mattress;
	}

	public String getMattressQtySize() {
		return this.mattressQtySize;
	}

	public void setMattressQtySize(String mattressQtySize) {
		this.mattressQtySize = mattressQtySize;
	}

	public String getMiscHouseholdItems() {
		return this.miscHouseholdItems;
	}

	public void setMiscHouseholdItems(String miscHouseholdItems) {
		this.miscHouseholdItems = miscHouseholdItems;
	}

	public String getRefridgerator() {
		return this.refridgerator;
	}

	public void setRefridgerator(String refridgerator) {
		this.refridgerator = refridgerator;
	}

	public String getStove() {
		return this.stove;
	}

	public void setStove(String stove) {
		this.stove = stove;
	}

	public String getRecliner() {
		return this.recliner;
	}

	public void setRecliner(String recliner) {
		this.recliner = recliner;
	}

	public String getSofa() {
		return this.sofa;
	}

	public void setSofa(String sofa) {
		this.sofa = sofa;
	}

	public String getLoveseat() {
		return this.loveseat;
	}

	public void setLoveseat(String loveseat) {
		this.loveseat = loveseat;
	}

	public String getWallUnit() {
		return this.wallUnit;
	}

	public void setWallUnit(String wallUnit) {
		this.wallUnit = wallUnit;
	}

	public String getTables() {
		return this.tables;
	}

	public void setTables(String tables) {
		this.tables = tables;
	}

	public String getChair() {
		return this.chair;
	}

	public void setChair(String chair) {
		this.chair = chair;
	}

	public String getTelevision() {
		return this.television;
	}

	public void setTelevision(String television) {
		this.television = television;
	}

	public String getTelevisionSize() {
		return this.televisionSize;
	}

	public void setTelevisionSize(String televisionSize) {
		this.televisionSize = televisionSize;
	}

	public String getElectronics() {
		return this.electronics;
	}

	public void setElectronics(String electronics) {
		this.electronics = electronics;
	}

	public String getWasher() {
		return this.washer;
	}

	public void setWasher(String washer) {
		this.washer = washer;
	}

	public String getDryer() {
		return this.dryer;
	}

	public void setDryer(String dryer) {
		this.dryer = dryer;
	}

	public String getExerciseEquipment() {
		return this.exerciseEquipment;
	}

	public void setExerciseEquipment(String exerciseEquipment) {
		this.exerciseEquipment = exerciseEquipment;
	}

	public String getSpecialNotes() {
		return this.specialNotes;
	}

	public void setSpecialNotes(String specialNotes) {
		this.specialNotes = specialNotes;
	}

	public String getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(String creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(String lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getFarmBase() {
		return this.farmBase;
	}

	public void setFarmBase(String farmBase) {
		this.farmBase = farmBase;
	}

	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	public String getChairType() {
		return this.chairType;
	}

	public void setChairType(String chairType) {
		this.chairType = chairType;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getBookcase() {
		return this.bookcase;
	}

	public void setBookcase(String bookcase) {
		this.bookcase = bookcase;
	}

	public String getOttoman() {
		return this.ottoman;
	}

	public void setOttoman(String ottoman) {
		this.ottoman = ottoman;
	}

	public String getMiscHouseholdItemQtySize() {
		return this.miscHouseholdItemQtySize;
	}

	public void setMiscHouseholdItemQtySize(String miscHouseholdItemQtySize) {
		this.miscHouseholdItemQtySize = miscHouseholdItemQtySize;
	}

	public String getWallUnitQtySize() {
		return this.wallUnitQtySize;
	}

	public void setWallUnitQtySize(String wallUnitQtySize) {
		this.wallUnitQtySize = wallUnitQtySize;
	}

	public String getGateCode() {
		return this.gateCode;
	}

	public void setGateCode(String gateCode) {
		this.gateCode = gateCode;
	}

}
